In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

### Install Dependencies

In [2]:
import pandas as pd
import os as os
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

/media/hassan-elkersh/OS/Users/User/OneDrive - Cairo University - Students/Graduation project/AutoPrepAI/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### Load Dataset

In [3]:
path = os.path.expanduser("Input/train.csv") 
df = pd.read_csv(path)
df.head()

,answers,query,finalpassage
0,"Kids who are bipolar, in their manic stages, v...",why do children get aggressive,"At the same time, despite claiming the review ..."
1,"Equifax, transunion and experian.",which credit bureau is used the most for auto ...,Best Answer: both of those answers are wrong. ...
2,"Women eat at least 1,200 calories daily and me...",what is the minimum healthy calorie intake,Safe Intakes. If you’re not supervised by a me...
3,Because Caffeine increases the stress hormone ...,why is coffee making gain weight,Is coffee making you fat? If you are overweigh...
4,Kent County,"what county is grand rapids, mi in","Located in Grand Rapids, Michigan, the 61st Di..."

### Select Only the `query` Column

In [4]:
df = df[['query']]
df.head()

                                               query
0                     why do children get aggressive
1  which credit bureau is used the most for auto ...
2         what is the minimum healthy calorie intake
3                   why is coffee making gain weight
4                 what county is grand rapids, mi in

### Get Number of Rows

In [5]:
len(df)

120000

### Display the First 20 Rows of the DataFrame

In [6]:
df.head(20)

                                                query
0                      why do children get aggressive
1   which credit bureau is used the most for auto ...
2          what is the minimum healthy calorie intake
3                    why is coffee making gain weight
4                  what county is grand rapids, mi in
5                  is bing rewards available in india
6   what temperature does it need to be to pour co...
7               how to clean stain on travertine tile
8                            what state is alameda in
9            salary sacrifice contributions age limit
10         what organelle generates energy for a cell
11                        what age can cats be spayed
12    how long to microwave a potato before baking it
13          triple bypass heart surgery success ratio
14                             test what is geography
15                      what are psilocybIN mushrooms
16                                    what are stupas
17                        what island is near florida
18        what temperature should a nursery school be
19                        what does a nerve look like

### Take a Random Sample

In [7]:
sample = df.sample(10000, random_state=42)

### Load Model

In [8]:
# model = SentenceTransformer("all-MiniLM-L6-v2")
model = SentenceTransformer("all-mpnet-base-v2")

### Embeddings

In [9]:
embeddings = model.encode(sample['query'].tolist(), show_progress_bar=True, convert_to_numpy=True, batch_size=64)

Batches:   0%|          | 0/157 [00:00<?, ?it/s]

Batches: 100%|██████████| 157/157 [00:04<00:00, 38.39it/s]

### Cosine Similarity

In [10]:
sim_matrix = cosine_similarity(embeddings)

### Detect Semantics

In [11]:
threshold = 0.8
for i in range(len(sample)):
    for j in range(i+1, len(sample)):
        if sim_matrix[i][j] > threshold:
            print(f"Pair found with similarity {sim_matrix[i][j]:.2f}:")
            print(f"Query 1: {sample.iloc[i]['query']}")
            print(f"Query 2: {sample.iloc[j]['query']}")
            print()

Pair found with similarity 0.98:
Query 1: The name Olmec means _____.
Query 2: the name olmec means

Pair found with similarity 0.93:
Query 1: define marketing procurement
Query 2: procurement marketing definition

Pair found with similarity 0.85:
Query 1: taklamakan desert definition
Query 2: where is taklimakan desert located

Pair found with similarity 0.85:
Query 1: what are good sources of calcium
Query 2: what food gives you calcium

Pair found with similarity 0.95:
Query 1: what is average salary for pharmacist
Query 2: what is pharmacists salary

Pair found with similarity 0.91:
Query 1: what is average salary for pharmacist
Query 2: how much does a pharmacist make

Pair found with similarity 0.83:
Query 1: how long can you keep eggs in the fridge
Query 2: how long do fresh eggs keep

Pair found with similarity 0.97:
Query 1: rita name meaning
Query 2: meaning of the name rita

Pair found with similarity 0.94:
Query 1: garage cost to build
Query 2: how much does it cost to build a garage

Pair found with similarity 0.97:
Query 1: how long do chicken eggs incubate
Query 2: how long do you incubate chicken eggs

Pair found with similarity 0.86:
Query 1: how long do chicken eggs incubate
Query 2: how long to hatch a chicken egg

Pair found with similarity 0.86:
Query 1: what is the normal fridge temperature
Query 2: how cold should fridge be

Pair found with similarity 0.84:
Query 1: what is the normal fridge temperature
Query 2: what should my refrigerator temp be set at

Pair found with similarity 0.89:
Query 1: platelets count normal range
Query 2: normal platelet level

Pair found with similarity 0.89:
Query 1: what is a spectrophotometer define
Query 2: what does a spectrophotometer do

Pair found with similarity 0.90:
Query 1: how long will food stay ok in freezer without power
Query 2: how long will food stay good in the fridge without power

Pair found with similarity 0.86:
Query 1: how long is a frozen whole turkey good for
Query 2: how long can frozen turkey be kept in freezer

Pair found with similarity 0.89:
Query 1: why was berlin wall built
Query 2: what was the berlin wall purpose

Pair found with similarity 0.81:
Query 1: what age can you leave a child home alone over night in california
Query 2: what age can i leave my child at home alone overnight

Pair found with similarity 0.85:
Query 1: good food for thyroid
Query 2: what foods activate the thyroid

Pair found with similarity 0.96:
Query 1: good food for thyroid
Query 2: foods that are good for the thyroid

Pair found with similarity 0.82:
Query 1: how do you measure an acre
Query 2: meaning of acre measurement

Pair found with similarity 0.88:
Query 1: how to roast a beef tenderloin
Query 2: how to cook a beef tenderloin

Pair found with similarity 0.81:
Query 1: at what temp. and how long to slow cook baby back ribs
Query 2: how to cook baby back ribs in slow cooker

Pair found with similarity 0.89:
Query 1: which type of fats are healthy
Query 2: which are good fats

Pair found with similarity 0.81:
Query 1: average cost for anytime fitness
Query 2: how much does it cost to tan at anytime fitness

Pair found with similarity 0.97:
Query 1: what is dealer
Query 2: what is a dealer

Pair found with similarity 1.00:
Query 1: what is the function of retinal pigment epithelium
Query 2: what is the function of the retinal pigment epithelium

Pair found with similarity 0.81:
Query 1: how much can you gift to someone tax free in the US
Query 2: how much money can you give a family member tax free

Pair found with similarity 0.87:
Query 1: how much can you gift to someone tax free in the US
Query 2: how much money can you gift without tax

Pair found with similarity 0.87:
Query 1: what is the largest city in eastern russia
Query 2: biggest cities in russia wiki

Pair found with similarity 0.81:
Query 1: average er visit cost
Query 2: how much is the average cost of an emergency room visit

Pair found with similarity 0.80:
Query 1: what is congenital deficiency
Query 2: what is congenital mean

Pair found with similarity 0.96:
Query 1: define selective attention
Query 2: what is selective attention

Pair found with similarity 0.83:
Query 1: average california state university professor salary
Query 2: how much does a university professor make in california

Pair found with similarity 0.93:
Query 1: why does ear itch inside
Query 2: why does the inside of my ears itch

Pair found with similarity 0.92:
Query 1: cost of repouring driveway
Query 2: cost of repaving driveway

Pair found with similarity 0.88:
Query 1: what is a blister with blood
Query 2: what does a blood blister look like

Pair found with similarity 0.85:
Query 1: what is the average lifespan of a laptop
Query 2: what is the usual lifespan of a laptop battery

Pair found with similarity 0.88:
Query 1: how long for fridge to cool
Query 2: how long does a new fridge take to cool

Pair found with similarity 0.84:
Query 1: what is the function of the golgi complex
Query 2: golgi apparatus (bodies) do what

Pair found with similarity 0.85:
Query 1: what do greenhouse gases cause
Query 2: what do greenhouses gases do

Pair found with similarity 0.88:
Query 1: tuition deduction for students
Query 2: deductible tuition expenses

Pair found with similarity 0.80:
Query 1: why did the boston massacre occur
Query 2: what happened during the actual event of the boston massacre

Pair found with similarity 0.95:
Query 1: maximum daily dosage for xanax
Query 2: recommended dosage for xanax daily

Pair found with similarity 0.94:
Query 1: average annual kwh per household
Query 2: average kwh usage per household

Pair found with similarity 0.87:
Query 1: what is the highest denomination bill in us currency
Query 2: what was the highest denomination bill printed

Pair found with similarity 0.80:
Query 1: where exactly in the cell does cellular respiration occur
Query 2: does cellular respiration take place in every cell of our body

Pair found with similarity 0.91:
Query 1: what is a spirit drink
Query 2: what is a spirit drink?

Pair found with similarity 0.81:
Query 1: cost to dig a pond
Query 2: cost to put a pond in backyard

Pair found with similarity 0.86:
Query 1: HOw long to cook lobster in boiling water
Query 2: how long do you cook lobster

Pair found with similarity 0.87:
Query 1: what was the effect of the treaty of versailles on germany
Query 2: how did the end of the treaty of versailles affect germany

Pair found with similarity 0.82:
Query 1: what is the typical price for normal sized patio deck
Query 2: cost of a deck vs patio

Pair found with similarity 0.85:
Query 1: cost to replace a thermostat for a furnace
Query 2: how much does it cost to replace a furnace

Pair found with similarity 0.87:
Query 1: how long to boiled eggs stay fresh
Query 2: how long are boiled eggs good for if refrigerated

Pair found with similarity 0.86:
Query 1: how long to boiled eggs stay fresh
Query 2: how long can you keep boiled eggs in fridge

Pair found with similarity 0.88:
Query 1: how long to boiled eggs stay fresh
Query 2: how long do hard boiled eggs keep fresh

Pair found with similarity 0.97:
Query 1: what is the function of hypothalamus
Query 2: what are the functions of the hypothalamus

Pair found with similarity 0.86:
Query 1: where is information contained in the dna
Query 2: where in the DNA molecule's is the genetic information located

Pair found with similarity 0.95:
Query 1: what is a white blood cell
Query 2: what does white blood cells mean

Pair found with similarity 0.89:
Query 1: folate what does it do?
Query 2: what is folate good for

Pair found with similarity 0.96:
Query 1: cost of a do it yourself divorce
Query 2: how much does a do it yourself divorce cost

Pair found with similarity 0.86:
Query 1: incubation period for influenza
Query 2: what is the incubation time for the flu

Pair found with similarity 0.82:
Query 1: cost to replace car clutch
Query 2: how much does it cost for clutch repair

Pair found with similarity 0.92:
Query 1: cost to replace car clutch
Query 2: how much does a clutch replacement cost

Pair found with similarity 0.91:
Query 1: what year shakespeare born
Query 2: what month was shakespeare born

Pair found with similarity 0.96:
Query 1: cost to declaw your cat
Query 2: how much to declaw a cat

Pair found with similarity 0.97:
Query 1: cost to declaw your cat
Query 2: how much is it to declaw a cat

Pair found with similarity 0.96:
Query 1: what foods are good to eat with diarrhea
Query 2: foods to eat when diarrhea

Pair found with similarity 0.96:
Query 1: how much does it take for a duck to egg to hatch
Query 2: how long does it take duck eggs to hatch

Pair found with similarity 0.88:
Query 1: how to cook salmon in oven
Query 2: how to cook baked salmon

Pair found with similarity 0.93:
Query 1: what is autoimmune disorder mean
Query 2: What is an autoimmune disease

Pair found with similarity 0.88:
Query 1: temperature when ovulation occurs
Query 2: body temperature ovulation

Pair found with similarity 0.83:
Query 1: what is predicate noun
Query 2: predicate adjective definition

Pair found with similarity 0.94:
Query 1: how old do you have to be to sign up for blood donation
Query 2: how old do you need to be to donate blood

Pair found with similarity 0.85:
Query 1: explanation of check routing numbers
Query 2: is  a check routing number

Pair found with similarity 0.81:
Query 1: what is pharmacists salary
Query 2: pay for pharmacists

Pair found with similarity 0.93:
Query 1: what is pharmacists salary
Query 2: how much does a pharmacist make

Pair found with similarity 0.89:
Query 1: dental implant cost per tooth
Query 2: how much do dental implants usually cost

Pair found with similarity 0.95:
Query 1: definition impact
Query 2: what is the definition of impact

Pair found with similarity 0.95:
Query 1: how big does a bearded dragon grow
Query 2: how big do bearded dragons get

Pair found with similarity 0.81:
Query 1: what is the normal width of a hallway
Query 2: what is the minimum hallway width

Pair found with similarity 0.85:
Query 1: solar panel plant cost
Query 2: cost to operate a solar power plant

Pair found with similarity 0.87:
Query 1: how long does the menstrual cycle last
Query 2: how long do periods last

Pair found with similarity 0.93:
Query 1: cost to advertise on facebook
Query 2: advertising costs on facebook

Pair found with similarity 0.91:
Query 1: cost to advertise on facebook
Query 2: what does it cost for a facebook ad

Pair found with similarity 0.98:
Query 1: cause of proteinuria
Query 2: what causes proteinuria

Pair found with similarity 0.95:
Query 1: where is benin
Query 2: where is benin located

Pair found with similarity 0.96:
Query 1: average salary for clinical psychologist
Query 2: annual salary of clinical psychologist

Pair found with similarity 0.88:
Query 1: what is a syllable
Query 2: what does syllables mean

Pair found with similarity 0.84:
Query 1: how much it cost to cremate a person
Query 2: how much for a basic cremation

Pair found with similarity 0.91:
Query 1: how much it cost to cremate a person
Query 2: what is cost of cremation

Pair found with similarity 0.86:
Query 1: how long to cook perfect hard boiled eggs
Query 2: how long do you have to cook eggs to be hard boiled

Pair found with similarity 0.82:
Query 1: how long to cook perfect hard boiled eggs
Query 2: how long do eggs have to boil to be hard boiled

Pair found with similarity 0.88:
Query 1: occupational physical therapist salary
Query 2: Occupational Therapist Salary

Pair found with similarity 0.81:
Query 1: how much do nurse practitioners make starting out
Query 2: how much do nurse practitioners make with an entry salary

Pair found with similarity 0.89:
Query 1: what oath does a doctor take
Query 2: what is the oath that dr and nurses take

Pair found with similarity 0.86:
Query 1: how long can i keep a rotisserie chicken in the refrigerator
Query 2: how long is rotisserie chicken good for in the freezer

Pair found with similarity 0.84:
Query 1: how long can i keep a rotisserie chicken in the refrigerator
Query 2: how long will a cooked rotisserie chicken keep in the fridge

Pair found with similarity 0.87:
Query 1: health benefits of clove essential
Query 2: health benefits of drinking clove

Pair found with similarity 0.88:
Query 1: advertising costs on facebook
Query 2: what does it cost for a facebook ad

Pair found with similarity 0.92:
Query 1: average cost of a small restaurant
Query 2: cost of building a small restaurant

Pair found with similarity 0.91:
Query 1: what does neurologist do
Query 2: what is neurologists

Pair found with similarity 0.96:
Query 1: paracord definition
Query 2: what is paracord

Pair found with similarity 0.84:
Query 1: what does parentheses mean in math
Query 2: what does parenthesis mean

Pair found with similarity 0.81:
Query 1: cost vinyl flooring
Query 2: labor cost to install vinyl flooring

Pair found with similarity 0.99:
Query 1: symbolic meaning of a circle
Query 2: symbolic meaning of circle

Pair found with similarity 0.86:
Query 1: average cost of bridal flowers
Query 2: how much do wedding flowers typically cost

Pair found with similarity 0.82:
Query 1: what do police wear to protect themselves
Query 2: police officer wear what

Pair found with similarity 0.85:
Query 1: who sang the cupid shuffle
Query 2: what year did the cupid shuffle come out

Pair found with similarity 0.81:
Query 1: how to qualify to become an american citizenship
Query 2: ELIGIBILITY how to get a citizenship card

Pair found with similarity 0.81:
Query 1: what the typical age for premature menopause
Query 2: age when women start menopause

Pair found with similarity 0.90:
Query 1: average salary for rn
Query 2: how much do rns make

Pair found with similarity 0.88:
Query 1: how much does it cost to have a face lift
Query 2: how much for facelift

Pair found with similarity 0.81:
Query 1: what are the different strategic roles of human resources
Query 2: what is human resource strategic direction

Pair found with similarity 0.86:
Query 1: how long are boiled eggs good for if refrigerated
Query 2: how long can you keep a hard boiled egg refrigerate

Pair found with similarity 0.92:
Query 1: how long are boiled eggs good for if refrigerated
Query 2: how long can you keep boiled eggs in fridge

Pair found with similarity 0.81:
Query 1: how long are boiled eggs good for if refrigerated
Query 2: how long do hard boiled eggs keep fresh

Pair found with similarity 0.81:
Query 1: dominant and recessive definition biology
Query 2: what is the difference between a dominant in a recessive allele

Pair found with similarity 0.98:
Query 1: price to install fence
Query 2: cost of installing fence

Pair found with similarity 0.89:
Query 1: functions of cytoplasm in animal cell
Query 2: function of cytoplasm

Pair found with similarity 0.86:
Query 1: average wage of a physical therapist
Query 2: average salary for a physical therapist assistant

Pair found with similarity 0.85:
Query 1: what does the name mahogany mean
Query 2: what does the color mahogany mean

Pair found with similarity 0.93:
Query 1: when did african american get the right to vote
Query 2: when did african american males get the right to vote

Pair found with similarity 0.91:
Query 1: when did african american get the right to vote
Query 2: when did black people get to vote

Pair found with similarity 0.97:
Query 1: where is indio calif
Query 2: where is indio ca

Pair found with similarity 0.80:
Query 1: cost to install central air and heat system
Query 2: cost of central air system

Pair found with similarity 0.85:
Query 1: average cost for wedding rings
Query 2: how much should an engagement ring cost

Pair found with similarity 0.84:
Query 1: what cause bipolar disorder manic depression
Query 2: what causes bipolar disorder

Pair found with similarity 0.91:
Query 1: normal temperature range reading for armpit
Query 2: normal body temperature fahrenheit armpit

Pair found with similarity 0.92:
Query 1: how long to roast boneless leg of lamb
Query 2: how long should you roast a boneless leg of lamb and what temperature

Pair found with similarity 0.91:
Query 1: how long to roast boneless leg of lamb
Query 2: how long to roast lamb leg

Pair found with similarity 0.89:
Query 1: where is siam
Query 2: what is siam

Pair found with similarity 0.97:
Query 1: domestic limited liability company definition
Query 2: what does domestic limited liability company mean

Pair found with similarity 0.98:
Query 1: how long do you bake a whole chicken in the oven
Query 2: how long should i cook a whole chicken in the oven

Pair found with similarity 0.81:
Query 1: what is the difference between a dominant in a recessive allele
Query 2: what is a dominant allele

Pair found with similarity 0.82:
Query 1: what is the difference between a dominant in a recessive allele
Query 2: What is the difference between a dominant and recessive trait?

Pair found with similarity 0.94:
Query 1: hydrocarbons definition
Query 2: what is hydrocarbon

Pair found with similarity 0.83:
Query 1: price of garage door installation
Query 2: how much should it cost to install a garage door opener

Pair found with similarity 0.83:
Query 1: how long do you incubate chicken eggs
Query 2: how long to hatch a chicken egg

Pair found with similarity 0.87:
Query 1: what is the appropriate amount of carbs per day
Query 2: how much carbs do i need

Pair found with similarity 0.85:
Query 1: what is the appropriate amount of carbs per day
Query 2: minimum carbs your body need a day

Pair found with similarity 0.85:
Query 1: where is your spleen located on your body
Query 2: what is your spleen

Pair found with similarity 0.88:
Query 1: how long do you have to be in college to be a physical therapist
Query 2: how long does it take to get a degree in physical therapy

Pair found with similarity 0.83:
Query 1: amazon card chase phone number
Query 2: chase card contact number

Pair found with similarity 0.90:
Query 1: where do timber wolves live
Query 2: what is a timber wolves habitat

Pair found with similarity 0.95:
Query 1: what is riboflavin?
Query 2: riboflavin what is it

Pair found with similarity 0.83:
Query 1: food sources for unsaturated fats
Query 2: dietary sources of trans and saturated fats

Pair found with similarity 0.81:
Query 1: what is a ligament
Query 2: what is the function of ligaments

Pair found with similarity 0.83:
Query 1: what is effect of super low blood sugar on the body
Query 2: what happens when your blood sugar is low

Pair found with similarity 0.92:
Query 1: what are common causes of eye infections
Query 2: what causes eye infection

Pair found with similarity 0.87:
Query 1: what is fetal alcohol syndrome in psychology
Query 2: what is fetal alcohol syndrome definition

Pair found with similarity 0.97:
Query 1: how long does grass take to germinate
Query 2: how long does grass seed take to germinate

Pair found with similarity 0.95:
Query 1: how long does grass take to germinate
Query 2: how quickly does grass seed germinate

Pair found with similarity 0.88:
Query 1: how much protein do you need to maintain muscle
Query 2: how much protein is needed to build muscle

Pair found with similarity 0.84:
Query 1: what temperature should i cook salmon at in the oven
Query 2: highest temperature to bake salmon

Pair found with similarity 0.89:
Query 1: how much do pay attorney for divorce case
Query 2: average cost for a divorce attorney

Pair found with similarity 0.80:
Query 1: what foods can lower blood sugar
Query 2: foods that curb glucose

Pair found with similarity 0.83:
Query 1: cost of cataract surgery with medicaid
Query 2: how much will medicare pay for cataract surgery

Pair found with similarity 0.89:
Query 1: how much does it cost for clutch repair
Query 2: how much does a clutch replacement cost

Pair found with similarity 0.83:

### Remove Duplicates

In [ ]:
to_drop = set()

threshold = 0.8
for i in range(len(sample)):
    for j in range(i + 1, len(sample)):
        if sim_matrix[i][j] > threshold:
            to_drop.add(j)

deduped_sample = sample.drop(sample.index[list(to_drop)]).reset_index(drop=True)

print(f"Original size: {len(sample)}")
print(f"After deduplication: {len(deduped_sample)}")

Original size: 10000
After deduplication: 9760
Data After deduplication:                                                   query
0               how to select multiple items in outlook
1     can an attorney terminate a contingency fee ag...
2                 sidvokodvo average weather conditions
3                       what do molecules do constantly
4                    what is a group of muskrats called
...                                                 ...
9755                            postage cost for letter
9756                      define spread plate technique
9757                          average ocean temperature
9758                where do atlantic silversides spawn
9759                 what does elizabethan england mean

[9760 rows x 1 columns]